# Generated by Django 3.0.7 on 2021-05-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparticipated',
            name='status',
            field=models.CharField(choices=[('Pass', 'pass'), ('Fail', 'fail')], default='Fail', max_length=100),
        ),
    ]
