# Generated by Django 3.0.7 on 2021-03-08 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_day_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
