# Generated by Django 3.0.7 on 2021-03-10 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_auto_20210309_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='userEnrolled',
            field=models.ManyToManyField(related_name='enrolled_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventmaytomany',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventmany', to='event.event'),
        ),
    ]
