# Generated by Django 3.0.7 on 2021-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210310_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attend_link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
