# Generated by Django 3.0.7 on 2021-03-13 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20210314_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_day_of_registration',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
