# Generated by Django 3.0.7 on 2021-04-14 11:25

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_discussioncomment_discussionpanel'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.CharField(default=chat.models.generate, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
    ]
