# Generated by Django 3.0.7 on 2021-04-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210414_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='code',
            new_name='chat_code',
        ),
    ]
