# Generated by Django 3.0.7 on 2021-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210414_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_code',
        ),
        migrations.AddField(
            model_name='chat',
            name='code_for_chat',
            field=models.CharField(default=3, max_length=10),
            preserve_default=False,
        ),
    ]
