# Generated by Django 3.0.7 on 2021-04-14 11:55

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210414_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='code_for_chat',
            field=models.CharField(default=chat.models.generate, max_length=10, unique=True),
        ),
    ]
