# Generated by Django 3.0.7 on 2021-03-22 20:42

import course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.Type_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='language_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='course.language_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='course_content', validators=[course.models.video_validator]),
        ),
    ]
