# Generated by Django 3.0.7 on 2021-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
