# Generated by Django 3.0.7 on 2021-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_image',
            field=models.ImageField(default='course_default.jpg', upload_to='course_thubnail'),
        ),
    ]
