# Generated by Django 3.0.7 on 2021-03-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_module_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course_associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='course.course'),
        ),
    ]
