# Generated by Django 3.0.7 on 2021-03-27 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_contentcompleted_coursecompleted_modulecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='studentCompleted',
            field=models.ManyToManyField(blank=True, default=None, related_name='completed_student_content', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='studentCompleted',
            field=models.ManyToManyField(blank=True, default=None, related_name='completed_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='studentCompleted',
            field=models.ManyToManyField(blank=True, default=None, related_name='completed_student_module', to=settings.AUTH_USER_MODEL),
        ),
    ]
