# Generated by Django 3.0.7 on 2021-05-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_discussioncomment_discussionpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpanel',
            name='courseId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
