# Generated by Django 3.0.7 on 2021-03-28 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recurit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='applied_people',
            field=models.ManyToManyField(blank=True, default=None, related_name='applied_people', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(default=None, to='recurit.language_category'),
        ),
    ]
