# Generated by Django 3.0.7 on 2021-03-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurit', '0002_auto_20210328_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='posted_on',
            field=models.DateField(auto_now=True),
        ),
    ]
