# Generated by Django 3.0.7 on 2021-03-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_languages_prefer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter_profile',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
