# Generated by Django 3.0.7 on 2021-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210328_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter_profile',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruiter_profile',
            name='country',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
