# Generated by Django 3.0.7 on 2021-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter_profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
