# Generated by Django 3.0.7 on 2021-05-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210520_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
